txt_path: ../data/owt-train.txt
bpe_path: ../data/owt-train.txt.bpe
bpe_shape_path: ../data/owt-train.txt.bpe.shape
valid_txt_path: ../data/owt-valid.txt
valid_bpe_path: ../data/owt-valid.txt.bpe
valid_bpe_shape_path: ../data/owt-valid.txt.bpe.shape
vocab_path: ../data/owt.vocab
merges_path: ../data/owt.merges
checkpoint_file: ../data/owt-train.txt.checkpoint
validaation_checkpoint_file: ../data/owt-train.txt.checkpoint
vocab_size: 10000
context_length: 256
d_model: 512
d_ff: 1344
rope_theta: 10000
num_layers: 4
num_heads: 16
batch_size: 64
num_batches: 2
training_steps: 1250